services:
  - type: web
    name: deadlines
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        value: https://deadlines.onrender.com
        sync: false
